//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StellarRoboProcess.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StellarRoboProcess.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   application/1d-interleaved-parityfec
        ///application/3gpdash-qoe-report+xml
        ///application/3gpp-ims+xml
        ///application/A2L
        ///application/activemessage
        ///application/activity+json
        ///application/alto-costmap+json
        ///application/alto-costmapfilter+json
        ///application/alto-directory+json
        ///application/alto-endpointprop+json
        ///application/alto-endpointpropparams+json
        ///application/alto-endpointcost+json
        ///application/alto-endpointcostparams+json
        ///application/alto-error+json
        ///application/alto-networkmapfilter+json
        ///application/alt [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string application {
            get {
                return ResourceManager.GetString("application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   audio/1d-interleaved-parityfec
        ///audio/32kadpcm
        ///audio/3gpp
        ///audio/3gpp2
        ///audio/aac
        ///audio/ac3
        ///audio/AMR
        ///audio/AMR-WB
        ///audio/amr-wb+
        ///audio/aptx
        ///audio/asc
        ///audio/ATRAC-ADVANCED-LOSSLESS
        ///audio/ATRAC-X
        ///audio/ATRAC3
        ///audio/basic
        ///audio/BV16
        ///audio/BV32
        ///audio/clearmode
        ///audio/CN
        ///audio/DAT12
        ///audio/dls
        ///audio/dsr-es201108
        ///audio/dsr-es202050
        ///audio/dsr-es202211
        ///audio/dsr-es202212
        ///audio/DV
        ///audio/DVI4
        ///audio/eac3
        ///audio/encaprtp
        ///audio/EVRC
        ///audio/EVRC-QCP
        ///audio/EVRC0
        ///audio/EVRC1
        ///audio/EVRCB
        ///audio/EVR [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string audio {
            get {
                return ResourceManager.GetString("audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   font/collection
        ///font/otf
        ///font/sfnt
        ///font/ttf
        ///font/woff
        ///font/woff2
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string font {
            get {
                return ResourceManager.GetString("font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   image/aces
        ///image/avci
        ///image/avcs
        ///image/bmp
        ///image/cgm
        ///image/dicom-rle
        ///image/emf
        ///image/example
        ///image/fits
        ///image/g3fax
        ///image/heic
        ///image/heic-sequence
        ///image/heif
        ///image/heif-sequence
        ///image/hej2k
        ///image/hsj2
        ///image/jls
        ///image/jp2
        ///image/jph
        ///image/jphc
        ///image/jpm
        ///image/jpx
        ///image/jxr
        ///image/jxrA
        ///image/jxrS
        ///image/jxsi
        ///image/jxss
        ///image/naplps
        ///image/png
        ///image/prs.btif
        ///image/prs.pti
        ///image/pwg-raster
        ///image/t38
        ///image/tiff
        ///image/tiff-fx
        ///image/vnd.adobe.photoshop
        ///image/vnd.airzip.accelerator.a [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   message/CPIM
        ///message/delivery-status
        ///message/disposition-notification
        ///message/example
        ///message/feedback-report
        ///message/global
        ///message/global-delivery-status
        ///message/global-disposition-notification
        ///message/global-headers
        ///message/http
        ///message/imdn+xml
        ///message/news
        ///message/s-http
        ///message/sip
        ///message/sipfrag
        ///message/tracking-status
        ///message/vnd.si.simp
        ///message/vnd.wfa.wsc
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   model/3mf
        ///model/example
        ///model/gltf-binary
        ///model/gltf+json
        ///model/iges
        ///model/stl
        ///model/vnd.collada+xml
        ///model/vnd.dwf
        ///model/vnd.flatland.3dml
        ///model/vnd.gdl
        ///model/vnd.gs-gdl
        ///model/vnd.gtw
        ///model/vnd.moml+xml
        ///model/vnd.mts
        ///model/vnd.opengex
        ///model/vnd.parasolid.transmit.binary
        ///model/vnd.parasolid.transmit.text
        ///model/vnd.rosette.annotated-data-model
        ///model/vnd.usdz+zip
        ///model/vnd.valve.source.compiled-map
        ///model/vnd.vtu
        ///model/x3d-vrml
        ///model/x3d+fastinfoset
        ///model/x3d+xml
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string model {
            get {
                return ResourceManager.GetString("model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   multipart/appledouble
        ///multipart/byteranges
        ///multipart/encrypted
        ///multipart/example
        ///multipart/form-data
        ///multipart/header-set
        ///multipart/multilingual
        ///multipart/related
        ///multipart/report
        ///multipart/signed
        ///multipart/vnd.bint.med-plus
        ///multipart/voice-message
        ///multipart/x-mixed-replace
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string multipart {
            get {
                return ResourceManager.GetString("multipart", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   text/1d-interleaved-parityfec
        ///text/cache-manifest
        ///text/calendar
        ///text/css
        ///text/csv
        ///text/csv-schema
        ///text/directory
        ///text/dns
        ///text/ecmascript
        ///text/encaprtp
        ///text/example
        ///text/flexfec
        ///text/fwdred
        ///text/grammar-ref-list
        ///text/html
        ///text/javascript
        ///text/jcr-cnd
        ///text/markdown
        ///text/mizar
        ///text/n3
        ///text/parameters
        ///text/provenance-notation
        ///text/prs.fallenstein.rst
        ///text/prs.lines.tag
        ///text/prs.prop.logic
        ///text/raptorfec
        ///text/RED
        ///text/rfc822-headers
        ///text/rtf
        ///text/rtp-enc-aescm128
        ///text/rtploopback
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   video/1d-interleaved-parityfec
        ///video/3gpp
        ///video/3gpp2
        ///video/3gpp-tt
        ///video/BMPEG
        ///video/BT656
        ///video/CelB
        ///video/DV
        ///video/encaprtp
        ///video/example
        ///video/flexfec
        ///video/H261
        ///video/H263
        ///video/H263-1998
        ///video/H263-2000
        ///video/H264
        ///video/H264-RCDO
        ///video/H264-SVC
        ///video/H265
        ///video/iso.segment
        ///video/JPEG
        ///video/jpeg2000
        ///video/mj2
        ///video/MP1S
        ///video/MP2P
        ///video/MP2T
        ///video/mp4
        ///video/MP4V-ES
        ///video/MPV
        ///video/mpeg4-generic
        ///video/nv
        ///video/ogg
        ///video/pointer
        ///video/quicktime
        ///video/raptorfec
        ///video/rtp [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
    }
}
